# Generated by Django 5.2.17 on 2026-09-16 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_workoutplan_exercises"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="activity_type",
            field=models.CharField(
                choices=[("strength", "Strength / weights"), ("cardio", "Cardio")],
                default="strength",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not set"),
                    ("compound", "Compound"),
                    ("isolation", "Isolation"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="primary_muscles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="WorkoutCardio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "minutes",
                    models.PositiveIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, max_length=2000)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.exercise"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardio",
                        to="core.workoutsession",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StepEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "steps",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(200000)]
                    ),
                ),
                ("note", models.TextField(blank=True, max_length=2000)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date"), name="steps_user_date"
                    )
                ],
            },
        ),
    ]
