# Generated by Django 5.2.17 on 2026-09-16 15:57

import django.core.validators
from django.db import migrations, models


def set_existing_cardio_duration(apps, schema_editor):
    apps.get_model("core", "Exercise").objects.filter(
        activity_type="cardio", default_minutes__isnull=True
    ).update(default_minutes=20)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_exercise_activity_type_exercise_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="default_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1440),
                ],
                verbose_name="Duration (minutes)",
            ),
        ),
        migrations.RunPython(set_existing_cardio_duration, migrations.RunPython.noop),
    ]
