# Generated by Django 5.2.17 on 2026-09-19 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_exercise_default_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritiontarget",
            name="sodium",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="nutritiontarget",
            name="sugar",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4000),
                ],
            ),
        ),
    ]
