# Generated by Django 5.2.17 on 2026-09-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_nutritiontarget_sodium_nutritiontarget_sugar"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodentry",
            name="ai_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
