# Generated by Django 5.2.17 on 2026-09-15 14:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("food", "Food Vision"),
                            ("workout", "Workout Analysis"),
                            ("body", "Body / Progress Analysis"),
                            ("daily", "Daily Summary"),
                            ("chat", "Coach Chat"),
                        ],
                        max_length=12,
                    ),
                ),
                ("dedupe", models.CharField(max_length=180, unique=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=12),
                ),
                ("lease_until", models.DateTimeField(null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=160)),
                ("result", models.JSONField(default=dict)),
                ("provider", models.CharField(blank=True, max_length=12)),
                ("model", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProviderModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("provider", models.CharField(max_length=12)),
                ("model", models.CharField(max_length=200)),
                ("available", models.BooleanField(default=True)),
                ("text_verified", models.BooleanField(default=False)),
                ("vision_verified", models.BooleanField(default=False)),
                ("tested_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="Not tested", max_length=60)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "model"), name="coach_unique_model"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("endpoint", models.URLField(max_length=2000, unique=True)),
                ("keys", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(max_length=12)),
                ("expected_version", models.PositiveIntegerField()),
                ("before", models.JSONField()),
                ("proposed", models.JSONField()),
                ("reason", models.TextField()),
                ("evidence", models.TextField()),
                ("decision", models.CharField(default="pending", max_length=12)),
                ("decided_at", models.DateTimeField(null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coaching.job"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task", models.CharField(max_length=12)),
                ("local_date", models.DateField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("content", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="coaching.job"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "task", "local_date", "version"),
                        name="coach_analysis_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("food", "Food Vision"),
                            ("workout", "Workout Analysis"),
                            ("body", "Body / Progress Analysis"),
                            ("daily", "Daily Summary"),
                            ("chat", "Coach Chat"),
                        ],
                        max_length=12,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coaching.providermodel",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "candidate"), name="coach_unique_route"
                    )
                ],
            },
        ),
    ]
