# Generated by Django 5.2.17 on 2026-09-15 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("task", models.CharField(max_length=12)),
                ("provider", models.CharField(max_length=12)),
                ("model", models.CharField(max_length=200)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("latency_ms", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=60)),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_attempts",
                        to="coaching.job",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
