# Generated by Django 5.2.17 on 2026-09-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaching", "0002_requestattempt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="task",
            field=models.CharField(
                choices=[
                    ("food", "Food Vision"),
                    ("workout", "Workout Analysis"),
                    ("body", "Body / Progress Analysis"),
                    ("daily", "Daily Summary"),
                    ("chat", "Coach Chat"),
                    ("exercise", "Exercise Metadata"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="taskroute",
            name="task",
            field=models.CharField(
                choices=[
                    ("food", "Food Vision"),
                    ("workout", "Workout Analysis"),
                    ("body", "Body / Progress Analysis"),
                    ("daily", "Daily Summary"),
                    ("chat", "Coach Chat"),
                    ("exercise", "Exercise Metadata"),
                ],
                max_length=12,
            ),
        ),
    ]
