"""Curated local nutrition reference for ingredient-level AI food analysis.

Values are derived from USDA FoodData Central public releases and standard
Thai food-composition reference tables. They are approximations for typical
prepared/cooked portions, not live API lookups or laboratory measurements.
"""

REFERENCE = {
    "cooked_white_rice": {
        "name_en": "cooked white rice",
        "name_th": "ข้าวสวย",
        "state": "cooked",
        "per_100g": {
            "kcal": 130,
            "protein": 2.7,
            "carbs": 28.0,
            "fat": 0.3,
            "fiber": 0.4,
            "sugar": 0.1,
            "sodium": 5,
        },
        "source": "USDA FDC (approx, cooked)",
        "aliases": ["rice", "ข้าว", "ข้าวสวย"],
        "dish": False,
        "typical_serving_g": 150,
    },
    "sticky_rice_cooked": {
        "name_en": "sticky rice (cooked)",
        "name_th": "ข้าวเหนียวนึ่ง",
        "state": "cooked",
        "per_100g": {
            "kcal": 160,
            "protein": 4.0,
            "carbs": 36.0,
            "fat": 0.3,
            "fiber": 0.9,
            "sugar": 0.1,
            "sodium": 5,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["sticky rice", "glutinous rice", "ข้าวเหนียว"],
        "dish": False,
        "typical_serving_g": 150,
    },
    "chicken_breast_cooked": {
        "name_en": "chicken breast cooked (skinless)",
        "name_th": "เนื้ออกไก่สุก ไม่มีหนัง",
        "state": "cooked, skinless",
        "per_100g": {
            "kcal": 165,
            "protein": 31.0,
            "carbs": 0.0,
            "fat": 3.6,
            "fiber": 0.0,
            "sugar": 0.0,
            "sodium": 74,
        },
        "source": "USDA FDC (approx, cooked)",
        "aliases": ["chicken breast", "อกไก่"],
        "dish": False,
        "typical_serving_g": 100,
    },
    "fried_chicken_battered": {
        "name_en": "fried chicken with skin and batter",
        "name_th": "ไก่ทอด มีหนังแป้งทอด",
        "state": "fried, skin+batter, edible incl. skin/batter, oil already in value",
        "per_100g": {
            "kcal": 290,
            "protein": 22.0,
            "carbs": 12.0,
            "fat": 19.0,
            "fiber": 0.8,
            "sugar": 0.3,
            "sodium": 600,
        },
        "source": "USDA FDC (approx, fried)",
        "aliases": ["fried chicken", "ไก่ทอด"],
        "dish": False,
        "typical_serving_g": 150,
    },
    "chicken_skin_fried": {
        "name_en": "fried chicken skin",
        "name_th": "หนังไก่ทอด",
        "state": "fried skin",
        "per_100g": {
            "kcal": 450,
            "protein": 20.0,
            "carbs": 8.0,
            "fat": 38.0,
            "fiber": 0.0,
            "sugar": 0.0,
            "sodium": 650,
        },
        "source": "USDA FDC (approx, fried)",
        "aliases": ["chicken skin", "หนังไก่"],
        "dish": False,
        "typical_serving_g": 30,
    },
    "pork_minced_cooked_stirfry": {
        "name_en": "stir-fried minced pork (~20% fat)",
        "name_th": "หมูสับผัด",
        "state": "cooked stir-fried minced pork ~20% fat",
        "per_100g": {
            "kcal": 250,
            "protein": 20.0,
            "carbs": 3.0,
            "fat": 18.0,
            "fiber": 0.0,
            "sugar": 0.0,
            "sodium": 380,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["minced pork", "pork", "หมูสับ", "หมู"],
        "dish": False,
        "typical_serving_g": 100,
    },
    "century_egg": {
        "name_en": "century egg (preserved duck egg)",
        "name_th": "ไข่เยี่ยวม้า",
        "state": "preserved duck egg",
        "per_100g": {
            "kcal": 130,
            "protein": 12.0,
            "carbs": 2.0,
            "fat": 9.0,
            "fiber": 0.0,
            "sugar": 0.5,
            "sodium": 700,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["preserved egg", "ไข่เยี่ยวม้า"],
        "dish": False,
        "typical_serving_g": 60,
    },
    "fried_egg": {
        "name_en": "fried egg",
        "name_th": "ไข่ดาวทอด",
        "state": "fried in oil",
        "per_100g": {
            "kcal": 210,
            "protein": 6.5,
            "carbs": 0.5,
            "fat": 19.0,
            "fiber": 0.0,
            "sugar": 0.2,
            "sodium": 210,
        },
        "source": "USDA FDC (approx, fried)",
        "aliases": ["fried egg", "ไข่ดาว"],
        "dish": False,
        "typical_serving_g": 50,
    },
    "boiled_egg": {
        "name_en": "boiled egg",
        "name_th": "ไข่ต้ม",
        "state": "boiled",
        "per_100g": {
            "kcal": 155,
            "protein": 13.0,
            "carbs": 1.1,
            "fat": 11.0,
            "fiber": 0.0,
            "sugar": 1.1,
            "sodium": 124,
        },
        "source": "USDA FDC (approx, cooked)",
        "aliases": ["boiled egg", "ไข่ต้ม"],
        "dish": False,
        "typical_serving_g": 50,
    },
    "sausage_thai": {
        "name_en": "Thai-style pork sausage (cooked)",
        "name_th": "ไส้กรอก",
        "state": "Thai-style pork sausage, cooked",
        "per_100g": {
            "kcal": 300,
            "protein": 13.0,
            "carbs": 12.0,
            "fat": 24.0,
            "fiber": 0.0,
            "sugar": 3.0,
            "sodium": 900,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["sausage", "ไส้กรอก"],
        "dish": False,
        "typical_serving_g": 50,
    },
    "fried_shallots": {
        "name_en": "crispy fried shallots",
        "name_th": "หอมเจียวทอด",
        "state": "crispy fried shallots",
        "per_100g": {
            "kcal": 570,
            "protein": 6.0,
            "carbs": 40.0,
            "fat": 44.0,
            "fiber": 8.0,
            "sugar": 8.0,
            "sodium": 30,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["fried shallots", "หอมเจียว"],
        "dish": False,
        "typical_serving_g": 15,
    },
    "sweet_chili_dipping_sauce": {
        "name_en": "sweet chili dipping sauce",
        "name_th": "น้ำจิ้มแจ่ว/น้ำจิ้มไก่",
        "state": "sauce",
        "per_100g": {
            "kcal": 130,
            "protein": 1.0,
            "carbs": 30.0,
            "fat": 0.5,
            "fiber": 0.5,
            "sugar": 26.0,
            "sodium": 800,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["sweet chili sauce", "chili dipping sauce", "น้ำจิ้มไก่", "น้ำจิ้มแจ่ว"],
        "dish": False,
        "typical_serving_g": 30,
    },
    "soy_fish_sauce_mix": {
        "name_en": "soy/fish sauce seasoning",
        "name_th": "น้ำปลา/ซีอิ๊วปรุง",
        "state": "seasoning sauce",
        "per_100g": {
            "kcal": 60,
            "protein": 8.0,
            "carbs": 3.0,
            "fat": 0.0,
            "fiber": 0.0,
            "sugar": 2.0,
            "sodium": 6000,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["fish sauce", "soy sauce", "น้ำปลา", "ซีอิ๊ว"],
        "dish": False,
        "typical_serving_g": 15,
    },
    "vegetable_cucumber": {
        "name_en": "raw vegetable / cucumber",
        "name_th": "ผัก/แตงกวา",
        "state": "raw veg side",
        "per_100g": {
            "kcal": 15,
            "protein": 0.7,
            "carbs": 3.0,
            "fat": 0.1,
            "fiber": 1.0,
            "sugar": 1.5,
            "sodium": 3,
        },
        "source": "USDA FDC (approx, raw)",
        "aliases": ["cucumber", "vegetable", "แตงกวา", "ผัก"],
        "dish": False,
        "typical_serving_g": 50,
    },
    "basil_stirfry_veg": {
        "name_en": "stir-fried basil / holy basil",
        "name_th": "ใบโหระพาผัด",
        "state": "stir-fried basil",
        "per_100g": {
            "kcal": 40,
            "protein": 2.0,
            "carbs": 5.0,
            "fat": 1.0,
            "fiber": 2.0,
            "sugar": 0.5,
            "sodium": 200,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["basil", "holy basil", "ใบโหระพา", "กะเพรา"],
        "dish": False,
        "typical_serving_g": 20,
    },
    "cooking_oil": {
        "name_en": "cooking oil",
        "name_th": "น้ำมันพืช",
        "state": "added oil only when not covered by prepared entries",
        "per_100g": {
            "kcal": 884,
            "protein": 0.0,
            "carbs": 0.0,
            "fat": 100.0,
            "fiber": 0.0,
            "sugar": 0.0,
            "sodium": 0,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["oil", "น้ำมัน"],
        "dish": False,
        "typical_serving_g": 15,
    },
    "coconut_milk_curry": {
        "name_en": "green curry with chicken (coconut milk based)",
        "name_th": "แกงเขียวหวาน",
        "state": "prepared curry with chicken",
        "per_100g": {
            "kcal": 130,
            "protein": 6.0,
            "carbs": 5.0,
            "fat": 10.0,
            "fiber": 1.0,
            "sugar": 2.0,
            "sodium": 400,
        },
        "source": "Thai FCD-style typical value",
        "aliases": ["green curry", "curry", "แกงเขียวหวาน"],
        "dish": True,
        "typical_serving_g": 250,
    },
    "ham": {
        "name_en": "ham",
        "name_th": "แฮม",
        "state": "cured ham",
        "per_100g": {
            "kcal": 145,
            "protein": 17.0,
            "carbs": 2.0,
            "fat": 8.0,
            "fiber": 0.0,
            "sugar": 1.0,
            "sodium": 1200,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["ham", "แฮม"],
        "dish": False,
        "typical_serving_g": 50,
    },
    # Noodles (cooked)
    "rice_noodles": {
        "name_en": "rice noodles (cooked)",
        "name_th": "เส้นข้าว",
        "state": "cooked",
        "per_100g": {
            "kcal": 109,
            "protein": 1.6,
            "carbs": 25.0,
            "fat": 0.3,
            "fiber": 1.0,
            "sugar": 0.0,
            "sodium": 6,
        },
        "source": "USDA FDC (approx, cooked)",
        "aliases": ["rice noodles", "เส้นข้าว", "ก๋วยเตี๋ยว"],
        "dish": False,
        "typical_serving_g": 150,
    },
    "egg_noodles": {
        "name_en": "egg noodles (cooked)",
        "name_th": "เส้นไข่",
        "state": "cooked",
        "per_100g": {
            "kcal": 138,
            "protein": 4.5,
            "carbs": 25.0,
            "fat": 2.1,
            "fiber": 1.7,
            "sugar": 0.5,
            "sodium": 60,
        },
        "source": "USDA FDC (approx, cooked)",
        "aliases": ["egg noodles", "เส้นไข่"],
        "dish": False,
        "typical_serving_g": 150,
    },
    "wheat_noodles_soup": {
        "name_en": "wheat noodles in soup (cooked)",
        "name_th": "เส้นบะหมี่ในซุป",
        "state": "cooked in seasoned broth",
        "per_100g": {
            "kcal": 110,
            "protein": 4.0,
            "carbs": 21.0,
            "fat": 1.5,
            "fiber": 1.5,
            "sugar": 0.3,
            "sodium": 400,
        },
        "source": "Thai typical value",
        "aliases": ["wheat noodles", "บะหมี่"],
        "dish": False,
        "typical_serving_g": 150,
    },
    "glass_noodles": {
        "name_en": "glass noodles (cooked)",
        "name_th": "วุ้นเส้น",
        "state": "cooked",
        "per_100g": {
            "kcal": 110,
            "protein": 0.2,
            "carbs": 27.0,
            "fat": 0.0,
            "fiber": 0.9,
            "sugar": 0.0,
            "sodium": 15,
        },
        "source": "USDA FDC (approx, cooked)",
        "aliases": ["glass noodles", "วุ้นเส้น"],
        "dish": False,
        "typical_serving_g": 100,
    },
    "instant_noodles": {
        "name_en": "instant noodles prepared with seasoning",
        "name_th": "บะหมี่กึ่งสำเร็จรูป",
        "state": "prepared, seasoning included",
        "per_100g": {
            "kcal": 138,
            "protein": 4.0,
            "carbs": 17.0,
            "fat": 5.0,
            "fiber": 1.8,
            "sugar": 1.0,
            "sodium": 860,
        },
        "source": "USDA FDC (approx, prepared)",
        "aliases": ["instant noodles", "mama", "บะหมี่กึ่งสำเร็จรูป"],
        "dish": False,
        "typical_serving_g": 250,
    },
    "wonton_noodle_soup": {
        "name_en": "wonton noodle soup (whole bowl)",
        "name_th": "บะหมี่เกี๊ยว",
        "state": "whole dish per ~450g bowl",
        "per_100g": {
            "kcal": 89,
            "protein": 6.0,
            "carbs": 11.0,
            "fat": 3.0,
            "fiber": 1.0,
            "sugar": 1.0,
            "sodium": 450,
        },
        "source": "Thai typical value",
        "aliases": ["wonton noodle soup", "บะหมี่เกี๊ยว"],
        "dish": True,
        "typical_serving_g": 450,
    },
    # Whole dishes
    "pad_thai": {
        "name_en": "pad thai",
        "name_th": "ผัดไทย",
        "state": "stir-fried rice noodle dish",
        "per_100g": {
            "kcal": 180,
            "protein": 8.0,
            "carbs": 24.0,
            "fat": 7.0,
            "fiber": 2.0,
            "sugar": 8.0,
            "sodium": 800,
        },
        "source": "Thai typical value",
        "aliases": ["pad thai", "ผัดไทย"],
        "dish": True,
        "typical_serving_g": 300,
    },
    "fried_rice": {
        "name_en": "fried rice",
        "name_th": "ข้าวผัด",
        "state": "stir-fried rice dish",
        "per_100g": {
            "kcal": 163,
            "protein": 5.5,
            "carbs": 22.0,
            "fat": 5.5,
            "fiber": 1.0,
            "sugar": 2.0,
            "sodium": 600,
        },
        "source": "Thai typical value",
        "aliases": ["fried rice", "ข้าวผัด"],
        "dish": True,
        "typical_serving_g": 350,
    },
    "basil_pork_rice": {
        "name_en": "basil pork with rice (kaprao moo)",
        "name_th": "กะเพราหมู + ข้าว",
        "state": "stir-fried basil pork served with rice",
        "per_100g": {
            "kcal": 155,
            "protein": 8.0,
            "carbs": 17.0,
            "fat": 6.0,
            "fiber": 1.2,
            "sugar": 2.0,
            "sodium": 500,
        },
        "source": "Thai typical value",
        "aliases": ["basil pork rice", "kaprao moo", "กะเพราหมู"],
        "dish": True,
        "typical_serving_g": 400,
    },
    "green_curry_rice": {
        "name_en": "green curry with rice",
        "name_th": "แกงเขียวหวาน + ข้าว",
        "state": "curry and rice together",
        "per_100g": {
            "kcal": 135,
            "protein": 6.0,
            "carbs": 15.0,
            "fat": 7.0,
            "fiber": 1.2,
            "sugar": 2.0,
            "sodium": 450,
        },
        "source": "Thai typical value",
        "aliases": ["green curry rice", "แกงเขียวหวานข้าว"],
        "dish": True,
        "typical_serving_g": 450,
    },
    "chicken_noodle_soup": {
        "name_en": "chicken noodle soup (bowl)",
        "name_th": "ก๋วยเตี๋ยวไก่",
        "state": "noodle soup dish",
        "per_100g": {
            "kcal": 105,
            "protein": 7.0,
            "carbs": 12.5,
            "fat": 3.2,
            "fiber": 0.8,
            "sugar": 0.8,
            "sodium": 380,
        },
        "source": "Thai typical value",
        "aliases": ["chicken noodle soup", "ก๋วยเตี๋ยวไก่"],
        "dish": True,
        "typical_serving_g": 450,
    },
    "tom_yum_soup": {
        "name_en": "tom yum soup",
        "name_th": "ต้มยำ",
        "state": "hot and sour soup",
        "per_100g": {
            "kcal": 45,
            "protein": 4.0,
            "carbs": 4.0,
            "fat": 2.0,
            "fiber": 0.5,
            "sugar": 2.0,
            "sodium": 700,
        },
        "source": "Thai typical value",
        "aliases": ["tom yum", "ต้มยำ"],
        "dish": True,
        "typical_serving_g": 350,
    },
    "chicken_rice": {
        "name_en": "Hainanese chicken rice",
        "name_th": "ข้าวมันไก่",
        "state": "steamed chicken with rice",
        "per_100g": {
            "kcal": 170,
            "protein": 9.0,
            "carbs": 20.0,
            "fat": 6.0,
            "fiber": 0.8,
            "sugar": 1.0,
            "sodium": 500,
        },
        "source": "Thai typical value",
        "aliases": ["chicken rice", "khao man gai", "ข้าวมันไก่"],
        "dish": True,
        "typical_serving_g": 400,
    },
    "chicken_sandwich": {
        "name_en": "chicken sandwich",
        "name_th": "แซนด์วิชไก่",
        "state": "sandwich with bread and chicken",
        "per_100g": {
            "kcal": 250,
            "protein": 13.0,
            "carbs": 26.0,
            "fat": 11.0,
            "fiber": 2.0,
            "sugar": 3.0,
            "sodium": 600,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["chicken sandwich", "แซนด์วิชไก่"],
        "dish": True,
        "typical_serving_g": 220,
    },
    "chicken_green_curry": {
        "name_en": "chicken green curry",
        "name_th": "แกงเขียวหวานไก่",
        "state": "curry dish without rice",
        "per_100g": {
            "kcal": 120,
            "protein": 9.0,
            "carbs": 5.0,
            "fat": 8.0,
            "fiber": 1.0,
            "sugar": 2.0,
            "sodium": 450,
        },
        "source": "Thai typical value",
        "aliases": ["chicken green curry", "แกงเขียวหวานไก่"],
        "dish": True,
        "typical_serving_g": 250,
    },
    # Sweets / fruit
    "chiffon_cake_plain": {
        "name_en": "plain chiffon cake",
        "name_th": "เค้กชิฟฟ่อนธรรมดา",
        "state": "baked cake",
        "per_100g": {
            "kcal": 290,
            "protein": 6.0,
            "carbs": 37.0,
            "fat": 14.0,
            "fiber": 0.5,
            "sugar": 22.0,
            "sodium": 300,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["chiffon cake", "เค้กชิฟฟ่อน"],
        "dish": False,
        "typical_serving_g": 80,
    },
    "coconut_chiffon_cake": {
        "name_en": "coconut chiffon cake",
        "name_th": "เค้กชิฟฟ่อนมะพร้าว",
        "state": "baked cake with coconut",
        "per_100g": {
            "kcal": 320,
            "protein": 5.0,
            "carbs": 33.0,
            "fat": 20.0,
            "fiber": 0.8,
            "sugar": 20.0,
            "sodium": 280,
        },
        "source": "Thai typical value",
        "aliases": ["coconut cake", "เค้กมะพร้าว"],
        "dish": False,
        "typical_serving_g": 90,
    },
    "banana": {
        "name_en": "banana",
        "name_th": "กล้วย",
        "state": "raw fruit",
        "per_100g": {
            "kcal": 89,
            "protein": 1.1,
            "carbs": 23.0,
            "fat": 0.3,
            "fiber": 2.6,
            "sugar": 12.0,
            "sodium": 1,
        },
        "source": "USDA FDC (approx, raw)",
        "aliases": ["banana", "กล้วย"],
        "dish": False,
        "typical_serving_g": 120,
    },
    "mango_sticky_rice": {
        "name_en": "mango sticky rice (serving)",
        "name_th": "ข้าวเหนียวมะม่วง",
        "state": "dessert per ~200g serving",
        "per_100g": {
            "kcal": 165,
            "protein": 3.0,
            "carbs": 28.0,
            "fat": 6.0,
            "fiber": 1.0,
            "sugar": 14.0,
            "sodium": 90,
        },
        "source": "Thai typical value",
        "aliases": ["mango sticky rice", "ข้าวเหนียวมะม่วง"],
        "dish": True,
        "typical_serving_g": 200,
    },
    # Drinks
    "protein_shake_ready": {
        "name_en": "ready-to-drink protein shake",
        "name_th": "โปรตีนเชค",
        "state": "beverage",
        "per_100g": {
            "kcal": 60,
            "protein": 8.9,
            "carbs": 2.0,
            "fat": 2.0,
            "fiber": 0.6,
            "sugar": 0.3,
            "sodium": 40,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["protein shake", "โปรตีน"],
        "dish": False,
        "typical_serving_g": 330,
    },
    "iced_coffee_milk": {
        "name_en": "iced coffee with milk",
        "name_th": "กาแฟเย็น",
        "state": "beverage with milk and sugar",
        "per_100g": {
            "kcal": 65,
            "protein": 1.5,
            "carbs": 11.0,
            "fat": 2.0,
            "fiber": 0.0,
            "sugar": 10.0,
            "sodium": 35,
        },
        "source": "Thai typical value",
        "aliases": ["iced coffee", "latte", "กาแฟเย็น"],
        "dish": False,
        "typical_serving_g": 300,
    },
    "soy_milk": {
        "name_en": "soy milk",
        "name_th": "น้ำเต้าหู้",
        "state": "beverage",
        "per_100g": {
            "kcal": 54,
            "protein": 3.3,
            "carbs": 6.0,
            "fat": 1.8,
            "fiber": 0.6,
            "sugar": 4.0,
            "sodium": 40,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["soy milk", "น้ำเต้าหู้"],
        "dish": False,
        "typical_serving_g": 250,
    },
    # Extras
    "broth_chicken": {
        "name_en": "chicken broth",
        "name_th": "น้ำซุปไก่",
        "state": "clear broth",
        "per_100g": {
            "kcal": 15,
            "protein": 1.5,
            "carbs": 1.0,
            "fat": 0.7,
            "fiber": 0.0,
            "sugar": 0.2,
            "sodium": 380,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["chicken broth", "broth", "น้ำซุป"],
        "dish": False,
        "typical_serving_g": 200,
    },
    "tofu": {
        "name_en": "tofu",
        "name_th": "เต้าหู้",
        "state": "cooked",
        "per_100g": {
            "kcal": 76,
            "protein": 8.0,
            "carbs": 1.9,
            "fat": 4.8,
            "fiber": 0.3,
            "sugar": 0.6,
            "sodium": 7,
        },
        "source": "USDA FDC (approx)",
        "aliases": ["tofu", "เต้าหู้"],
        "dish": False,
        "typical_serving_g": 100,
    },
    "mushroom": {
        "name_en": "mushroom",
        "name_th": "เห็ด",
        "state": "cooked",
        "per_100g": {
            "kcal": 22,
            "protein": 3.1,
            "carbs": 3.3,
            "fat": 0.3,
            "fiber": 1.0,
            "sugar": 2.0,
            "sodium": 5,
        },
        "source": "USDA FDC (approx, cooked)",
        "aliases": ["mushroom", "เห็ด"],
        "dish": False,
        "typical_serving_g": 50,
    },
}


def lookup(key):
    """Return a reference entry by exact key or alias match."""
    if key in REFERENCE:
        return REFERENCE[key]
    key_norm = str(key).strip().lower()
    for ref_key, entry in REFERENCE.items():
        if key_norm == ref_key.lower():
            return entry
        for alias in entry.get("aliases", []):
            if key_norm == alias.lower():
                return entry
    return None


def table_for_prompt():
    """Compact reference table for embedding in AI prompts."""
    lines = []
    for ref_key, entry in REFERENCE.items():
        p = entry["per_100g"]
        dish_note = ""
        if entry.get("dish"):
            dish_note = f" [dish, ~{entry.get('typical_serving_g', '')}g serving]"
        line = (
            f"{ref_key} | {entry['name_th']} ({entry['state']}){dish_note} | "
            f"{p['kcal']}kcal P{p['protein']} C{p['carbs']} F{p['fat']} per 100g | "
            f"sodium {p['sodium']}mg"
        )
        lines.append(line)
    return "\n".join(lines)
